### ISSUE TITLE
Does not work with Unreal 4.9.2

### ISSUE THREAD

**Issue by Fubaxiusz** [kamesenin/Rook#1]
Plugin is not working with Unreal 4.9.2 version, which is the last one not requiring Visual Studio for building project to EXE. Is it possible to make it work with 4.9?

**Comment by kamesenin** [comment]
On it.

**Comment by Fubaxiusz** [comment]
Great!
I've noticed just yesterday that newest 4.18.1 also builds projects without Visual Studio.
Where can I give some feedback regarding the plugin?

**Comment by kamesenin** [comment]
Hey. Are You still need it for 4.9.2 ? If You want to give feedback write to kamesenin@gmail.com . Cheers

**Comment by Fubaxiusz** [comment]
I don't need it for 4.9.2, just 4.18.1 :) Thanks
